name: soumu-code-normalizer
version: 0.1.0.0
github: "aiya000/soumu-code-normalizer"
license: MIT
author: "aiya000"
maintainer: "aiya000.develop@gmail.com"
copyright: "aiya000"
category: Simple
synopsis: 総務省が提供する全国地方公共団体コードのxlsからjsonに変換する。
description: Please see the README on GitHub at https://github.com/aiya000/hs-soumu-code-normalizer

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  soumu-code-normalizer-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - soumu-code-normalizer
